package com.unisociesc.SistemaFolhaPagamento.application.mapper;

import com.unisociesc.SistemaFolhaPagamento.application.dto.CollaboratorRequestDto;
import com.unisociesc.SistemaFolhaPagamento.application.dto.CollaboratorResponseDto;
import com.unisociesc.SistemaFolhaPagamento.application.dto.commissioned.request.CommissionedRequestDto;
import com.unisociesc.SistemaFolhaPagamento.application.dto.commissioned.response.CommissionedResponseDto;
import com.unisociesc.SistemaFolhaPagamento.application.dto.production.request.ProductionRequestDto;
import com.unisociesc.SistemaFolhaPagamento.application.dto.production.response.ProductionResponseDto;
import com.unisociesc.SistemaFolhaPagamento.application.dto.standard.request.StandardRequestDto;
import com.unisociesc.SistemaFolhaPagamento.application.dto.standard.response.StandardResponseDto;
import com.unisociesc.SistemaFolhaPagamento.domain.entity.Collaborator;
import com.unisociesc.SistemaFolhaPagamento.domain.entity.CommissionedContributor;
import com.unisociesc.SistemaFolhaPagamento.domain.entity.ProductionCollaborator;
import com.unisociesc.SistemaFolhaPagamento.domain.entity.StandardContributor;
import org.springframework.stereotype.Component;

/**
 * Mapper responsible for converting between collaborator DTOs and domain entities.
 *
 * <p>Handles all three collaborator subtypes — standard, commissioned, and production —
 * using {@code instanceof} pattern matching to determine the correct conversion logic
 * for each type.</p>
 *
 * @author Vinicius dos Santos Zapella
 * @version 1.0
 * @since 26/03/2026
 * @see Collaborator
 * @see CollaboratorRequestDto
 * @see CollaboratorResponseDto
 */
@Component
public class CollaboratorMapper {

    /**
     * Converts a {@link CollaboratorRequestDto} into its corresponding {@link Collaborator} entity.
     *
     * <p>The conversion is determined by the concrete type of the request DTO:</p>
     * <ul>
     *   <li>{@link StandardRequestDto} → {@link StandardContributor}</li>
     *   <li>{@link CommissionedRequestDto} → {@link CommissionedContributor}</li>
     *   <li>{@link ProductionRequestDto} → {@link ProductionCollaborator}</li>
     * </ul>
     *
     * <p>The entity ID is always set to {@code null}, as it will be generated by the database on save.</p>
     *
     * @param collaboratorRequestDto the request DTO to be converted
     * @return the corresponding {@link Collaborator} entity
     * @throws IllegalArgumentException if the DTO type is not recognized
     */
    public Collaborator toEntity(CollaboratorRequestDto collaboratorRequestDto) {
        if (collaboratorRequestDto instanceof StandardRequestDto standardRequestDto) {
            return new StandardContributor(
                    null,
                    standardRequestDto.registrationNumber(),
                    standardRequestDto.name()
            );
        }

        if (collaboratorRequestDto instanceof CommissionedRequestDto commissionedRequestDto) {
            return new CommissionedContributor(
                    null,
                    commissionedRequestDto.registrationNumber(),
                    commissionedRequestDto.name(),
                    commissionedRequestDto.totalSales(),
                    commissionedRequestDto.percentageCommission()
            );
        }

        if (collaboratorRequestDto instanceof ProductionRequestDto productionRequestDto) {
            return new ProductionCollaborator(
                    null,
                    productionRequestDto.registrationNumber(),
                    productionRequestDto.name(),
                    productionRequestDto.valuePerPiece(),
                    productionRequestDto.quantityProduced()
            );
        }

        throw new IllegalArgumentException("Invalid employee type");
    }

    /**
     * Converts a {@link Collaborator} entity into its corresponding {@link CollaboratorResponseDto}.
     *
     * <p>The conversion is determined by the concrete type of the entity:</p>
     * <ul>
     *   <li>{@link StandardContributor} → {@link StandardResponseDto} (extras always {@code 0.0})</li>
     *   <li>{@link CommissionedContributor} → {@link CommissionedResponseDto}</li>
     *   <li>{@link ProductionCollaborator} → {@link ProductionResponseDto}</li>
     * </ul>
     *
     * @param collaborator the entity to be converted
     * @param baseSalary   the base salary configured for the company
     * @param extra        the additional amount beyond the base salary (bonus or commission)
     * @param finalSalary  the total calculated salary
     * @return the corresponding {@link CollaboratorResponseDto}
     * @throws IllegalArgumentException if the entity type is not recognized
     */
    public CollaboratorResponseDto toResponse(
            Collaborator collaborator,
            Double baseSalary,
            Double extra,
            Double finalSalary
    ) {
        if (collaborator instanceof StandardContributor) {
            return new StandardResponseDto(
                    collaborator.getName(),
                    collaborator.getRegistrationNumber(),
                    baseSalary,
                    0.0,
                    finalSalary
            );
        }

        if (collaborator instanceof CommissionedContributor) {
            return new CommissionedResponseDto(
                    collaborator.getName(),
                    collaborator.getRegistrationNumber(),
                    baseSalary,
                    extra,
                    finalSalary
            );
        }

        if (collaborator instanceof ProductionCollaborator) {
            return new ProductionResponseDto(
                    collaborator.getName(),
                    collaborator.getRegistrationNumber(),
                    baseSalary,
                    extra,
                    finalSalary
            );
        }

        throw new IllegalArgumentException("Unknown entity type");
    }
}