package com.unisociesc.SistemaFolhaPagamento.domain.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Abstract base entity representing a collaborator in the payroll system.
 *
 * <p>This class uses the {@link InheritanceType#SINGLE_TABLE} JPA strategy,
 * meaning all collaborator subtypes are stored in a single database table
 * ({@code collaborator_table}), distinguished by the {@code bond_type} discriminator column.</p>
 *
 * <p>Known subtypes:</p>
 * <ul>
 *   <li>{@link StandardContributor} — receives only the base salary</li>
 *   <li>{@link CommissionedContributor} — receives base salary plus a sales commission</li>
 *   <li>{@link ProductionCollaborator} — receives base salary plus a production bonus</li>
 * </ul>
 *
 * @author Vinicius dos Santos Zapella
 * @version 1.0
 * @since 26/03/2026
 */
@Entity
@Table(name = "collaborator_table")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "bond_type", discriminatorType = DiscriminatorType.STRING)
public abstract class Collaborator {

    /**
     * Unique identifier of the collaborator, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique registration number assigned to the collaborator.
     * Cannot be null and must be unique across all records.
     */
    @Column(unique = true, nullable = false)
    private Integer registrationNumber;

    /**
     * Full name of the collaborator.
     * Cannot be null or blank.
     */
    @Column(nullable = false)
    private String name;

}